# Generated by Django 3.2.4 on 2021-06-29 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_auto_20210629_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.position'),
        ),
    ]
