# Generated by Django 3.2.4 on 2021-06-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_alter_employees_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Position',
            field=models.CharField(max_length=100),
        ),
    ]
